<?php
use App\Colony;
use App\ColonyScope;
use App\SettlementType;
use Illuminate\Database\Seeder;

class TestColonyTableSeeder extends Seeder {

	public function run() {
	DB::table('colonies')->delete();
	$colonyScope=ColonyScope::find(1);
	$settlementTypes=SettlementType::find(1);

		//Colony::create(array('zip' =>'94500' ,'name' => '', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ANTORCHISTA                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO CORDOBA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => '30 CABALLEROS (DANTE DELGADO)      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ACCION Y SERVICIO                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGRARIA                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGRICOLA STA. MARIA                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGUA FRIA                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGUILLON GUZMAN                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGUSTIN MILLAN                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALAMEDA                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALBERTO ROSALES O STA. BRIGIDA     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALIANZA                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALIANZA POPULAR                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMP. MIRAFLORES II STA. CECILIA    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION 20 DE NOVIEMBRE         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION CARRILES (BARRANCA)     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION COLORINES               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION MARGARITA MORAN         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION SAN IGNACIO             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION ZACATEPEC               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ANTONIO LUNA                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ANTORCHISTA                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ARAUCARIAS                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'AUTOPISTA                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO DE LAS CONCHITAS            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO DE SAN MIGUEL               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO DE SAN PEDRO                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO SAN JUAN                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'BENITO JUAREZ                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'BETANIA                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'BRILLANTE CRUCERO                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'BUGAMBILIA                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CANDIDO AGUILAR                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CARACAS                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CARRILES                           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CENTRO                             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CIRCUITO CAMPESTRE                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COG.CUAUHTEMOC                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. A. ROSALES                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. AMPLIACION ZACATEPEC          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. ARAUCARIAS                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. BETANIA                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DANTE DELGADO O 30 CABALLEROS ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DE LOS DEPORTES               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DEL MAESTRO                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DEL SOL                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. EL DORADO                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. EL TREBOL                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. FEDERAL                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. GOMEZ MORIN                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. JARDINES DEL SUR              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA ARCADIA                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA PALMA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA SELVA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA UNION                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LAS AZUCENAS                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LOS CEDROS                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LOS ROBLES-RESERVA TERRITORIAL','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. NUEVA                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. ROBLES                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SAN MARCIAL                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SAN MIGUEL                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SAN NICOLAS                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SANTA AURELIA                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SANTA TERESA                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. ZACATEPEC AEROPISTA           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL.. FEDERAL                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL..LOS ROBLES - RESERVA TERRITORI','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL.A.ROSALES                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL.RANCHO SAN FELIPE              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLONIA EL PEDREGAL                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLONIA EL ZOPILOTE                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLONIA LAZARO CARDENAS            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLORINES                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COMUNIDAD LA REFORMA               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COMUNIDAD SANTA ELENA              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. 20 DE NOVIEMBRE              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. CUAHUTEMOC                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. EL BAJIO                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. EL GALLEGO                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. KILOMETRO 14                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. MATLAQUIAHUITL               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. PALMA Y MONTERO              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. TLACOTENGO                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CORDOBA                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CORDOBESES ILUSTRES                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'COSALTEPEC                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CRUCERO NACIONAL                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'CRUCERO NAL. O EL PUEBLITO         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'DANTE DELGADO O 30 CABALLEROS      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'DE LOS DEPORTES                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'DEL MAESTRO                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'DIVINA MORALES DE GTZ. BARRIOS     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'DOS CAMINOS                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL BARREAL                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL CARMEN                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL DORADO                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL GIRASOL                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL MANANTIAL                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL MIRADOR                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL PALOMAR                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL PEDREGAL                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL PUEBLITO                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL REFUGIO                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL SOL                             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL TREBOL                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL ZOPILOTE                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ELECTRICISTAS                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'EMILIO CARRANZA                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ESPERANZA                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'F. STA. INES                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FEDERAL                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FLORES MAGON                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRAC. LOS PINOS                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC LAS RUBELINAS                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC LOMAS DEL ANGEL              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC LOS ALMENDROS                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC VILLA ALEGRA                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC VILLAS DE SAN ISIDRO         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC, SANTA CLARA                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.  VICTORIA                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. AGUA FRIA                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ALAMEDA                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ALAMOS                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ALPHA                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ANA PAULA                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ARBOLEDAS                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. AVE PARAISO                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. BELLA VISTA                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. BETANIA                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. BUGAMBILIAS                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CALINDA                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CAMPESTRE CORDOBES          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CAÑAVERAL                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CHEEL                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CIPRES                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CLUB CAMPESTRE              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. DEL ANGEL                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL BOSQUE                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL CAMPANARIO               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL DIAMANTE                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL HUERTO                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL MILAGRO                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL PORTAL                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ELIZABETH                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. FINCA REAL                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. FUENTES                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. FUENTES DEL CAMPESTRE       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. GUADALUPE                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDIN                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDINES DE LA ALAMEDA      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDINES DE SAN DIMAS       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDINES DEL SUR            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LA HERRADURA                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LA VICTORIA                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMA ALTA                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMA DE LOS ANGELES         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMAS                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMAS VERDES                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ALAMOS                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ALAMOS                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ANGELES                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ANTURIOS                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS CAFETALES               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS CEDROS                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS FRESNOS                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS NARDOS                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS OLIVOS                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS PINOS                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ROBLES                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS TULIPANES               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. NUEVO CORDOBA               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. NVA. ELIZABETH              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ORQUIDEAS                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PARAISO ESCONDIDO           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PASO COYOL                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PRADERAS DE SAN MIGUELITO   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PUENTES                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PUERTA DEL SOL              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN ANGEL                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN ISIDRO                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN JORGE                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN JOSE                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN LUIS                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN NICOLAS                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SANTA CECILIA               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SANTA CLARA                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SANTA MONICA                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VICTORIA                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA ALEGRA                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA DE LA LUZ             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA LAS FLORES            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA REAL                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA VERDE                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLAS DE HUILANGO          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLAS DE LA LUZ            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLAS DE SAN ISIDRO        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VIRGINIA                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.GUADALUPE                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.VICTORIA                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.VILLA  LAS FLORES            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRANCISCO MOROSINI                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD (ARBOLEDAS)            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD-MANGOS                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD-ROBLES                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FREDEPO                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FTE. A SAN ROMAN                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'FUNDADORES 30 CABALLEROS           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'GOMEZ MORIN                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'GUADALUPE BARREAL                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'HEBERTO CASTILLO MARTINEZ          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'HUILANGO                           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDECO SHANGRI-LA                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDECO TOXPAN                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDEPENDENCIA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDUSTRIAL                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'INF. SAN NICOLAS                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'JARDINES DE SAN DIMAS              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'JARDINES DEL SUR                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'JOSE MARIA MORELOS                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUAREZ                             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUNTO A JARDINES DE LA ALAMEDA     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUNTO JARDINES DE LA ALAMEDA       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUSTO SIERRA                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'KILOMETRO 15                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ARCADIA                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA BUGAMBILIA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ESMERALDA                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ESMERALDA                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ESTACION                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA FORTALEZA                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA JOYITA                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA LUZ FRANCISCO I. MADERO         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA LUZ PALOTAL                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA PALMA                           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA POSTA                           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA SELVA                           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA SIDRA                           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA TRINIDAD CHICA                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS AZUCENAS                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS BRISAS                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS BUGAMBILIAS                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS CONCHITAS                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS ESTACIONES                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS FLORES                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS MARGARITAS                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS PALMAS                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAZARO CARDENAS                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LIENZO CHARRO                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. ACAYOTLA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. CERVANTES Y LOZADA            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. LAGUNILLA                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. LOMA CHICA                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. LOMA GRANDE                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. OJO DE AGUA                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. PAREDONES                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. QUINTA MANZANA                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. SAN PEDRO Y ANEXAS            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. TINAJITAS                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOMA DE LOS ANGELES                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOMAS DEL PEDREGAL                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOMBARDO TOLEDANO                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOPEZ ARIAS                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS ALAMOS                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS ARCOS                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS CEDROS                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS FILTROS                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS FILTROS                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS LIRIOS                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS MANGOS                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS NARANJOS                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS ROBLES - RESERVA TERRITORIAL   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS TULIPANES                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MARGARITA MORAN                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MARQUEZHOYOS                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MEXICO                             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MEXICO, D.F.                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MIGUEL ALEMAN                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MIGUEL HIDALGO                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MIRAFLORES                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MODERNA                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MUJERES INSURGENTES                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'MURILLO VIDAL                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVA ESPERANZA                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO CORDOBA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO CORDOBA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO SAN JOSE                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO SAN RAFAEL                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO TOXPAN                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PABLO L SIDAR                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PALENQUE PALOTAL                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PARAISO                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PARDO                              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PENJAMO                            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PETROLERA                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PINO SUAREZ                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PLAZA FUNDADORES                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'POPULAR LA POSTA                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PRAXEDIS GUERRERO                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PUEBLO QUIETO                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'PUENTE BEJUCO                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO GUADALUPE                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO LA ESMERALDA                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO MIRANDA                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO SAN FELIPE                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO SANTA MONICA                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO STA. CLARA                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESERVA TERRITORIAL                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESID. EL BRILLANTE                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL AGUA FRIA              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL CAMPESTRE              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL EL BRILLANTE           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL LA SALLE               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL LA TRINIDAD CHICA      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL LAS PALMAS             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL SAN LONGINOS           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL SHANGRI-LA             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL TRINIDAD LA CHICA      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'RODRIGUEZ CLARA                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN CAYETANO                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN CRISTOBAL                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN DIMAS                          ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN FCO. TOXPAN                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN FRANCISCO TOXPAN               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN IGNACIO                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN ISIDRO PALOTAL                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JOSE                           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JOSE DE TAPIA                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JOSE LOMA GRANDE               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JUAN NEPOMUCENO                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MARTIN                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MATIAS                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MIGUEL                         ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MIGUELITO                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN NICOLAS                        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN RAFAEL CALERIA                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA AURELIA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA CRUZ BUENAVISTA              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA FE                           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA LETICIA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA MATILDE                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA ROSALIA                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA TERESA                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTO DOMINGO                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SHANGRILA LAS FUENTES              ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'SIERRA DEL GALLEGO                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'STA. CECILIA                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'TECAMA - CALERIA                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'TOXPAN                             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'TRANCA DE TUBOS O ZACATEPEC        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'U. ALEJANDRA RGUEZ.                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'U. HAB. LOS ARCOS                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD ARBOLEDAS                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD CECADYS                     ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD CORDOBA 2000                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL DORADO                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL HUERTO                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL PEDREGAL                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL TREBOL                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL ZOPILOTE                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD ENRIQUE RAMOS               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD ERASTO PORTILLA             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD HUILANGO 3000               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD JARDIN                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LA POSTA                    ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LA VICTORIA                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LAS CAÑAS                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LAS FUENTES                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOMA LINDA                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOMAS DE SAN MARCIAL        ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOS CEREZOS                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOS ROBLES                  ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD POPULAR LA POSTA            ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD RINCON DEL BOSQUE           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SAN NICOLAS                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SAN ROMAN                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SANTA CLARA                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SANTA MARGARITA             ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SHANGRI-LA LAS FUENTES      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD VILLA  LAS FLORES           ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD VISTA HERMOSA               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD. LOS ALAMOS                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNION Y PROGRESO                   ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'URSULO GALVAN                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'VALLE DEL SOL                      ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'VALLE DORADO                       ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'VENUSTIANO CARRANZA                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'VILLA DE LOS FRESNOS               ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'VILLAS DE HUILANGO                 ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ZACATEPEC AEROPISTA                ','sector_id'=>1));
		Colony::create(array('zip' =>'94500' ,'name' => 'ZONA INDUSTRIAL                    ','sector_id'=>1));	

		$colonies=Colony::all();
		foreach ($colonies as $colony) {
			$colony->colonyScopes()->associate(ColonyScope::find(1))->save();
			$colony->settlementTypes()->associate(SettlementType::find(1))->save();
		}
}
}