<?php
use App\Colony;
use App\ColonyScope;
use App\SettlementType;
use Illuminate\Database\Seeder;

class TestColonyTableSeeder extends Seeder {

	public function run() {
	DB::table('colonies')->delete();
	$colonyScope=ColonyScope::find(1);
	$settlementTypes=SettlementType::find(1);

		//Colony::create(array('zip' =>'94500' ,'name' => '', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ANTORCHISTA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO CORDOBA                     '));
		Colony::create(array('zip' =>'94500' ,'name' => '30 CABALLEROS (DANTE DELGADO)      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ACCION Y SERVICIO                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGRARIA                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGRICOLA STA. MARIA                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGUA FRIA                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGUILLON GUZMAN                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGUSTIN MILLAN                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALAMEDA                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALBERTO ROSALES O STA. BRIGIDA     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALIANZA                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALIANZA POPULAR                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMP. MIRAFLORES II STA. CECILIA    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION 20 DE NOVIEMBRE         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION CARRILES (BARRANCA)     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION COLORINES               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION MARGARITA MORAN         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION SAN IGNACIO             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION ZACATEPEC               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ANTONIO LUNA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ANTORCHISTA                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ARAUCARIAS                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'AUTOPISTA                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO DE LAS CONCHITAS            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO DE SAN MIGUEL               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO DE SAN PEDRO                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO SAN JUAN                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'BENITO JUAREZ                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'BETANIA                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'BRILLANTE CRUCERO                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'BUGAMBILIA                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CANDIDO AGUILAR                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CARACAS                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CARRILES                           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CENTRO                             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CIRCUITO CAMPESTRE                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COG.CUAUHTEMOC                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. A. ROSALES                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. AMPLIACION ZACATEPEC          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. ARAUCARIAS                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. BETANIA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DANTE DELGADO O 30 CABALLEROS '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DE LOS DEPORTES               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DEL MAESTRO                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DEL SOL                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. EL DORADO                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. EL TREBOL                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. FEDERAL                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. GOMEZ MORIN                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. JARDINES DEL SUR              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA ARCADIA                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA PALMA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA SELVA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA UNION                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LAS AZUCENAS                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LOS CEDROS                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LOS ROBLES-RESERVA TERRITORIAL'));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. NUEVA                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. ROBLES                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SAN MARCIAL                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SAN MIGUEL                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SAN NICOLAS                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SANTA AURELIA                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SANTA TERESA                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. ZACATEPEC AEROPISTA           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL.. FEDERAL                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL..LOS ROBLES - RESERVA TERRITORI'));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL.A.ROSALES                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL.RANCHO SAN FELIPE              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLONIA EL PEDREGAL                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLONIA EL ZOPILOTE                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLONIA LAZARO CARDENAS            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLORINES                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COMUNIDAD LA REFORMA               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COMUNIDAD SANTA ELENA              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. 20 DE NOVIEMBRE              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. CUAHUTEMOC                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. EL BAJIO                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. EL GALLEGO                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. KILOMETRO 14                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. MATLAQUIAHUITL               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. PALMA Y MONTERO              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. TLACOTENGO                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CORDOBA                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CORDOBESES ILUSTRES                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'COSALTEPEC                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CRUCERO NACIONAL                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'CRUCERO NAL. O EL PUEBLITO         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'DANTE DELGADO O 30 CABALLEROS      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'DE LOS DEPORTES                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'DEL MAESTRO                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'DIVINA MORALES DE GTZ. BARRIOS     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'DOS CAMINOS                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL BARREAL                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL CARMEN                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL DORADO                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL GIRASOL                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL MANANTIAL                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL MIRADOR                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL PALOMAR                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL PEDREGAL                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL PUEBLITO                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL REFUGIO                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL SOL                             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL TREBOL                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL ZOPILOTE                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ELECTRICISTAS                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'EMILIO CARRANZA                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ESPERANZA                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'F. STA. INES                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FEDERAL                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FLORES MAGON                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRAC. LOS PINOS                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC LAS RUBELINAS                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC LOMAS DEL ANGEL              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC LOS ALMENDROS                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC VILLA ALEGRA                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC VILLAS DE SAN ISIDRO         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC, SANTA CLARA                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.  VICTORIA                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. AGUA FRIA                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ALAMEDA                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ALAMOS                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ALPHA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ANA PAULA                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ARBOLEDAS                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. AVE PARAISO                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. BELLA VISTA                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. BETANIA                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. BUGAMBILIAS                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CALINDA                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CAMPESTRE CORDOBES          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CAÑAVERAL                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CHEEL                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CIPRES                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CLUB CAMPESTRE              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. DEL ANGEL                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL BOSQUE                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL CAMPANARIO               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL DIAMANTE                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL HUERTO                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL MILAGRO                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL PORTAL                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ELIZABETH                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. FINCA REAL                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. FUENTES                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. FUENTES DEL CAMPESTRE       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. GUADALUPE                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDIN                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDINES DE LA ALAMEDA      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDINES DE SAN DIMAS       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDINES DEL SUR            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LA HERRADURA                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LA VICTORIA                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMA ALTA                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMA DE LOS ANGELES         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMAS                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMAS VERDES                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ALAMOS                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ALAMOS                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ANGELES                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ANTURIOS                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS CAFETALES               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS CEDROS                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS FRESNOS                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS NARDOS                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS OLIVOS                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS PINOS                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ROBLES                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS TULIPANES               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. NUEVO CORDOBA               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. NVA. ELIZABETH              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ORQUIDEAS                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PARAISO ESCONDIDO           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PASO COYOL                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PRADERAS DE SAN MIGUELITO   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PUENTES                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PUERTA DEL SOL              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN ANGEL                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN ISIDRO                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN JORGE                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN JOSE                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN LUIS                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN NICOLAS                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SANTA CECILIA               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SANTA CLARA                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SANTA MONICA                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VICTORIA                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA ALEGRA                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA DE LA LUZ             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA LAS FLORES            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA REAL                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA VERDE                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLAS DE HUILANGO          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLAS DE LA LUZ            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLAS DE SAN ISIDRO        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VIRGINIA                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.GUADALUPE                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.VICTORIA                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.VILLA  LAS FLORES            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRANCISCO MOROSINI                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD (ARBOLEDAS)            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD-MANGOS                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD-ROBLES                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FREDEPO                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FTE. A SAN ROMAN                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'FUNDADORES 30 CABALLEROS           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'GOMEZ MORIN                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'GUADALUPE BARREAL                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'HEBERTO CASTILLO MARTINEZ          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'HUILANGO                           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDECO SHANGRI-LA                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDECO TOXPAN                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDEPENDENCIA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDUSTRIAL                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'INF. SAN NICOLAS                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'JARDINES DE SAN DIMAS              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'JARDINES DEL SUR                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'JOSE MARIA MORELOS                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUAREZ                             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUNTO A JARDINES DE LA ALAMEDA     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUNTO JARDINES DE LA ALAMEDA       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUSTO SIERRA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'KILOMETRO 15                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ARCADIA                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA BUGAMBILIA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ESMERALDA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ESMERALDA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ESTACION                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA FORTALEZA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA JOYITA                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA LUZ FRANCISCO I. MADERO         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA LUZ PALOTAL                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA PALMA                           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA POSTA                           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA SELVA                           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA SIDRA                           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA TRINIDAD CHICA                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS AZUCENAS                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS BRISAS                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS BUGAMBILIAS                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS CONCHITAS                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS ESTACIONES                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS FLORES                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS MARGARITAS                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS PALMAS                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAZARO CARDENAS                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LIENZO CHARRO                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. ACAYOTLA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. CERVANTES Y LOZADA            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. LAGUNILLA                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. LOMA CHICA                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. LOMA GRANDE                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. OJO DE AGUA                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. PAREDONES                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. QUINTA MANZANA                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. SAN PEDRO Y ANEXAS            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. TINAJITAS                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOMA DE LOS ANGELES                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOMAS DEL PEDREGAL                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOMBARDO TOLEDANO                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOPEZ ARIAS                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS ALAMOS                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS ARCOS                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS CEDROS                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS FILTROS                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS FILTROS                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS LIRIOS                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS MANGOS                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS NARANJOS                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS ROBLES - RESERVA TERRITORIAL   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS TULIPANES                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MARGARITA MORAN                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MARQUEZHOYOS                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MEXICO                             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MEXICO, D.F.                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MIGUEL ALEMAN                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MIGUEL HIDALGO                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MIRAFLORES                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MODERNA                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MUJERES INSURGENTES                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'MURILLO VIDAL                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVA ESPERANZA                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO CORDOBA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO CORDOBA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO SAN JOSE                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO SAN RAFAEL                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO TOXPAN                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PABLO L SIDAR                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PALENQUE PALOTAL                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PARAISO                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PARDO                              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PENJAMO                            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PETROLERA                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PINO SUAREZ                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PLAZA FUNDADORES                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'POPULAR LA POSTA                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PRAXEDIS GUERRERO                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PUEBLO QUIETO                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'PUENTE BEJUCO                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO GUADALUPE                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO LA ESMERALDA                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO MIRANDA                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO SAN FELIPE                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO SANTA MONICA                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO STA. CLARA                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESERVA TERRITORIAL                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESID. EL BRILLANTE                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL AGUA FRIA              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL CAMPESTRE              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL EL BRILLANTE           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL LA SALLE               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL LA TRINIDAD CHICA      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL LAS PALMAS             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL SAN LONGINOS           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL SHANGRI-LA             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL TRINIDAD LA CHICA      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'RODRIGUEZ CLARA                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN CAYETANO                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN CRISTOBAL                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN DIMAS                          '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN FCO. TOXPAN                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN FRANCISCO TOXPAN               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN IGNACIO                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN ISIDRO PALOTAL                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JOSE                           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JOSE DE TAPIA                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JOSE LOMA GRANDE               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JUAN NEPOMUCENO                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MARTIN                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MATIAS                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MIGUEL                         '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MIGUELITO                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN NICOLAS                        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN RAFAEL CALERIA                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA AURELIA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA CRUZ BUENAVISTA              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA FE                           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA LETICIA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA MATILDE                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA ROSALIA                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA TERESA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTO DOMINGO                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SHANGRILA LAS FUENTES              '));
		Colony::create(array('zip' =>'94500' ,'name' => 'SIERRA DEL GALLEGO                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'STA. CECILIA                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'TECAMA - CALERIA                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'TOXPAN                             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'TRANCA DE TUBOS O ZACATEPEC        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'U. ALEJANDRA RGUEZ.                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'U. HAB. LOS ARCOS                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD ARBOLEDAS                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD CECADYS                     '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD CORDOBA 2000                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL DORADO                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL HUERTO                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL PEDREGAL                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL TREBOL                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL ZOPILOTE                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD ENRIQUE RAMOS               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD ERASTO PORTILLA             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD HUILANGO 3000               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD JARDIN                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LA POSTA                    '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LA VICTORIA                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LAS CAÑAS                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LAS FUENTES                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOMA LINDA                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOMAS DE SAN MARCIAL        '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOS CEREZOS                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOS ROBLES                  '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD POPULAR LA POSTA            '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD RINCON DEL BOSQUE           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SAN NICOLAS                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SAN ROMAN                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SANTA CLARA                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SANTA MARGARITA             '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SHANGRI-LA LAS FUENTES      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD VILLA  LAS FLORES           '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD VISTA HERMOSA               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD. LOS ALAMOS                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNION Y PROGRESO                   '));
		Colony::create(array('zip' =>'94500' ,'name' => 'URSULO GALVAN                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'VALLE DEL SOL                      '));
		Colony::create(array('zip' =>'94500' ,'name' => 'VALLE DORADO                       '));
		Colony::create(array('zip' =>'94500' ,'name' => 'VENUSTIANO CARRANZA                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'VILLA DE LOS FRESNOS               '));
		Colony::create(array('zip' =>'94500' ,'name' => 'VILLAS DE HUILANGO                 '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ZACATEPEC AEROPISTA                '));
		Colony::create(array('zip' =>'94500' ,'name' => 'ZONA INDUSTRIAL                    '));	

		$colonies=Colony::all();
		foreach ($colonies as $colony) {
			$colony->colonyScopes()->associate(ColonyScope::find(1))->save();
			$colony->settlementTypes()->associate(SettlementType::find(1))->save();
		}
}
}