<?php
use App\Colony;
use Illuminate\Database\Seeder;

class TestColonyTableSeeder extends Seeder {

	public function run() {
	DB::table('colonies')->delete();
		//Colony::create(array('zip' =>'94500' ,'name' => '', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ANTORCHISTA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO CORDOBA                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => '30 CABALLEROS (DANTE DELGADO)      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ACCION Y SERVICIO                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGRARIA                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGRICOLA STA. MARIA                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGUA FRIA                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGUILLON GUZMAN                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AGUSTIN MILLAN                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALAMEDA                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALBERTO ROSALES O STA. BRIGIDA     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALIANZA                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ALIANZA POPULAR                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMP. MIRAFLORES II STA. CECILIA    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION 20 DE NOVIEMBRE         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION CARRILES (BARRANCA)     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION COLORINES               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION MARGARITA MORAN         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION SAN IGNACIO             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AMPLIACION ZACATEPEC               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ANTONIO LUNA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ANTORCHISTA                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ARAUCARIAS                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'AUTOPISTA                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO DE LAS CONCHITAS            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO DE SAN MIGUEL               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO DE SAN PEDRO                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'BARRIO SAN JUAN                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'BENITO JUAREZ                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'BETANIA                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'BRILLANTE CRUCERO                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'BUGAMBILIA                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CANDIDO AGUILAR                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CARACAS                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CARRILES                           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CENTRO                             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CIRCUITO CAMPESTRE                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COG.CUAUHTEMOC                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. A. ROSALES                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. AMPLIACION ZACATEPEC          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. ARAUCARIAS                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. BETANIA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DANTE DELGADO O 30 CABALLEROS ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DE LOS DEPORTES               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DEL MAESTRO                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. DEL SOL                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. EL DORADO                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. EL TREBOL                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. FEDERAL                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. GOMEZ MORIN                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. JARDINES DEL SUR              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA ARCADIA                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA PALMA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA SELVA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LA UNION                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LAS AZUCENAS                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LOS CEDROS                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. LOS ROBLES-RESERVA TERRITORIAL', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. NUEVA                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. ROBLES                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SAN MARCIAL                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SAN MIGUEL                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SAN NICOLAS                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SANTA AURELIA                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. SANTA TERESA                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL. ZACATEPEC AEROPISTA           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL.. FEDERAL                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL..LOS ROBLES - RESERVA TERRITORI', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL.A.ROSALES                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COL.RANCHO SAN FELIPE              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLONIA EL PEDREGAL                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLONIA EL ZOPILOTE                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLONIA LAZARO CARDENAS            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COLORINES                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COMUNIDAD LA REFORMA               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COMUNIDAD SANTA ELENA              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. 20 DE NOVIEMBRE              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. CUAHUTEMOC                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. EL BAJIO                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. EL GALLEGO                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. KILOMETRO 14                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. MATLAQUIAHUITL               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. PALMA Y MONTERO              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CONG. TLACOTENGO                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CORDOBA                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CORDOBESES ILUSTRES                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'COSALTEPEC                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CRUCERO NACIONAL                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'CRUCERO NAL. O EL PUEBLITO         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'DANTE DELGADO O 30 CABALLEROS      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'DE LOS DEPORTES                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'DEL MAESTRO                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'DIVINA MORALES DE GTZ. BARRIOS     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'DOS CAMINOS                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL BARREAL                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL CARMEN                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL DORADO                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL GIRASOL                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL MANANTIAL                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL MIRADOR                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL PALOMAR                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL PEDREGAL                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL PUEBLITO                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL REFUGIO                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL SOL                             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL TREBOL                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EL ZOPILOTE                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ELECTRICISTAS                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'EMILIO CARRANZA                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ESPERANZA                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'F. STA. INES                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FEDERAL                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FLORES MAGON                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRAC. LOS PINOS                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC LAS RUBELINAS                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC LOMAS DEL ANGEL              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC LOS ALMENDROS                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC VILLA ALEGRA                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC VILLAS DE SAN ISIDRO         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC, SANTA CLARA                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.  VICTORIA                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. AGUA FRIA                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ALAMEDA                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ALAMOS                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ALPHA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ANA PAULA                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ARBOLEDAS                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. AVE PARAISO                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. BELLA VISTA                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. BETANIA                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. BUGAMBILIAS                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CALINDA                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CAMPESTRE CORDOBES          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CAÑAVERAL                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CHEEL                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CIPRES                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. CLUB CAMPESTRE              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. DEL ANGEL                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL BOSQUE                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL CAMPANARIO               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL DIAMANTE                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL HUERTO                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL MILAGRO                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. EL PORTAL                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ELIZABETH                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. FINCA REAL                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. FUENTES                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. FUENTES DEL CAMPESTRE       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. GUADALUPE                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDIN                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDINES DE LA ALAMEDA      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDINES DE SAN DIMAS       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. JARDINES DEL SUR            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LA HERRADURA                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LA VICTORIA                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMA ALTA                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMA DE LOS ANGELES         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMAS                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOMAS VERDES                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ALAMOS                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ALAMOS                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ANGELES                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ANTURIOS                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS CAFETALES               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS CEDROS                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS FRESNOS                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS NARDOS                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS OLIVOS                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS PINOS                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS ROBLES                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. LOS TULIPANES               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. NUEVO CORDOBA               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. NVA. ELIZABETH              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. ORQUIDEAS                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PARAISO ESCONDIDO           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PASO COYOL                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PRADERAS DE SAN MIGUELITO   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PUENTES                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. PUERTA DEL SOL              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN ANGEL                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN ISIDRO                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN JORGE                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN JOSE                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN LUIS                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SAN NICOLAS                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SANTA CECILIA               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SANTA CLARA                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. SANTA MONICA                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VICTORIA                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA ALEGRA                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA DE LA LUZ             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA LAS FLORES            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA REAL                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLA VERDE                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLAS DE HUILANGO          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLAS DE LA LUZ            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VILLAS DE SAN ISIDRO        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC. VIRGINIA                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.GUADALUPE                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.VICTORIA                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRACC.VILLA  LAS FLORES            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRANCISCO MOROSINI                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD (ARBOLEDAS)            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD-MANGOS                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FRATERNIDAD-ROBLES                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FREDEPO                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FTE. A SAN ROMAN                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'FUNDADORES 30 CABALLEROS           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'GOMEZ MORIN                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'GUADALUPE BARREAL                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'HEBERTO CASTILLO MARTINEZ          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'HUILANGO                           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDECO SHANGRI-LA                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDECO TOXPAN                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDEPENDENCIA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'INDUSTRIAL                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'INF. SAN NICOLAS                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'JARDINES DE SAN DIMAS              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'JARDINES DEL SUR                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'JOSE MARIA MORELOS                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUAREZ                             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUNTO A JARDINES DE LA ALAMEDA     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUNTO JARDINES DE LA ALAMEDA       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'JUSTO SIERRA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'KILOMETRO 15                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ARCADIA                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA BUGAMBILIA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ESMERALDA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ESMERALDA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA ESTACION                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA FORTALEZA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA JOYITA                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA LUZ FRANCISCO I. MADERO         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA LUZ PALOTAL                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA PALMA                           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA POSTA                           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA SELVA                           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA SIDRA                           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LA TRINIDAD CHICA                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS AZUCENAS                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS BRISAS                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS BUGAMBILIAS                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS CONCHITAS                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS ESTACIONES                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS FLORES                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS MARGARITAS                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAS PALMAS                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LAZARO CARDENAS                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LIENZO CHARRO                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. ACAYOTLA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. CERVANTES Y LOZADA            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. LAGUNILLA                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. LOMA CHICA                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. LOMA GRANDE                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. OJO DE AGUA                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. PAREDONES                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. QUINTA MANZANA                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. SAN PEDRO Y ANEXAS            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOC. TINAJITAS                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOMA DE LOS ANGELES                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOMAS DEL PEDREGAL                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOMBARDO TOLEDANO                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOPEZ ARIAS                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS ALAMOS                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS ARCOS                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS CEDROS                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS FILTROS                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS FILTROS                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS LIRIOS                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS MANGOS                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS NARANJOS                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS ROBLES - RESERVA TERRITORIAL   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'LOS TULIPANES                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MARGARITA MORAN                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MARQUEZHOYOS                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MEXICO                             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MEXICO, D.F.                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MIGUEL ALEMAN                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MIGUEL HIDALGO                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MIRAFLORES                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MODERNA                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MUJERES INSURGENTES                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'MURILLO VIDAL                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVA ESPERANZA                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO CORDOBA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO CORDOBA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO SAN JOSE                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO SAN RAFAEL                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'NUEVO TOXPAN                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PABLO L SIDAR                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PALENQUE PALOTAL                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PARAISO                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PARDO                              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PENJAMO                            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PETROLERA                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PINO SUAREZ                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PLAZA FUNDADORES                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'POPULAR LA POSTA                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PRAXEDIS GUERRERO                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PUEBLO QUIETO                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'PUENTE BEJUCO                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO GUADALUPE                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO LA ESMERALDA                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO MIRANDA                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO SAN FELIPE                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO SANTA MONICA                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RANCHO STA. CLARA                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESERVA TERRITORIAL                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESID. EL BRILLANTE                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL AGUA FRIA              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL CAMPESTRE              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL EL BRILLANTE           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL LA SALLE               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL LA TRINIDAD CHICA      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL LAS PALMAS             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL SAN LONGINOS           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL SHANGRI-LA             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RESIDENCIAL TRINIDAD LA CHICA      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'RODRIGUEZ CLARA                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN CAYETANO                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN CRISTOBAL                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN DIMAS                          ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN FCO. TOXPAN                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN FRANCISCO TOXPAN               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN IGNACIO                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN ISIDRO PALOTAL                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JOSE                           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JOSE DE TAPIA                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JOSE LOMA GRANDE               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN JUAN NEPOMUCENO                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MARTIN                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MATIAS                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MIGUEL                         ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN MIGUELITO                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN NICOLAS                        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SAN RAFAEL CALERIA                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA AURELIA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA CRUZ BUENAVISTA              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA FE                           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA LETICIA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA MATILDE                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA ROSALIA                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTA TERESA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SANTO DOMINGO                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SHANGRILA LAS FUENTES              ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'SIERRA DEL GALLEGO                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'STA. CECILIA                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'TECAMA - CALERIA                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'TOXPAN                             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'TRANCA DE TUBOS O ZACATEPEC        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'U. ALEJANDRA RGUEZ.                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'U. HAB. LOS ARCOS                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD ARBOLEDAS                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD CECADYS                     ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD CORDOBA 2000                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL DORADO                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL HUERTO                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL PEDREGAL                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL TREBOL                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD EL ZOPILOTE                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD ENRIQUE RAMOS               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD ERASTO PORTILLA             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD HUILANGO 3000               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD JARDIN                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LA POSTA                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LA VICTORIA                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LAS CAÑAS                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LAS FUENTES                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOMA LINDA                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOMAS DE SAN MARCIAL        ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOS CEREZOS                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD LOS ROBLES                  ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD POPULAR LA POSTA            ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD RINCON DEL BOSQUE           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SAN NICOLAS                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SAN ROMAN                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SANTA CLARA                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SANTA MARGARITA             ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD SHANGRI-LA LAS FUENTES      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD VILLA  LAS FLORES           ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD VISTA HERMOSA               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNIDAD. LOS ALAMOS                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'UNION Y PROGRESO                   ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'URSULO GALVAN                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'VALLE DEL SOL                      ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'VALLE DORADO                       ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'VENUSTIANO CARRANZA                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'VILLA DE LOS FRESNOS               ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'VILLAS DE HUILANGO                 ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ZACATEPEC AEROPISTA                ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));
		Colony::create(array('zip' =>'94500' ,'name' => 'ZONA INDUSTRIAL                    ', 'colony_scope_id' => 1, 'settlement_type_id' => 1,	));	
	}
}